# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode61
sudo: required
rvm:
- 2.1.2
before_install:
- echo Downloading Butler
install:
- sudo ./Scripts/install.sh
