# Example Travis config. See the entire example: https://github.com/JonathanPorta/ci-build

language: objective-c
osx_image: xcode61
sudo: required
rvm:
- 2.1.2
before_install:
- echo Downloading Butler
- curl -o butler https://dl.itch.ovh/butler/darwin-amd64/head/butler
- echo Downloading Unity 5.5.0f3
- curl -o Unity.pkg http://netstorage.unity3d.com/unity/3757309da7e7/MacEditorInstaller/Unity-5.5.0f3.pkg

install:
- sudo installer -dumplog -package Unity.pkg -target /
- export PATH="$PATH:./butler"

before_script:
- project="testci"

script:
- /Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -nographics -silent-crashes -logFile $(pwd)/unity.log -projectPath $(pwd) -buildWindowsPlayer "$(pwd)/Build/windows/$project.exe" -quit

after_success:
- echo "Succes !"

deploy: 
- butler push ./ mrvil/testci:win32
